name: detox_e2e

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Detox CLI
        run: npm install detox-cli --global

      - name: Install Detox Utils
        run: brew tap wix/brew && brew install applesimutils

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: 3.x
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Fetch Simulator Build
        run: node fetchSimulatorBuild.js

      - name: Detox - Run E2E Tests
        run: |
          detox test --configuration ios.sim.debug --cleanup --loglevel trace
