name: Web E2E Test

on:
  workflow_dispatch:

env:
  TARGET: ${{ github.event.inputs.target || 'release' }}

jobs:
  web-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm i

      - name: Checkout spelieve
        uses: actions/checkout@v3
        with:
          repository: Ayato-kosaka/spelieve
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: spelieve

      - name: Start spelieve web
        run: "cd spelieve && npm ci && npm i -g expo-cli && expo web &"

      - name: Checkout spelieve-secret
        uses: actions/checkout@v3
        with:
          repository: Ayato-kosaka/spelieve-secret
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: spelieve/spelieve-secret
      - run: "mv ./spelieve/spelieve-secret/spelieve-frontend/${{ env.TARGET }}/ENV.ts ./spelieve/src"
      - run: "rm -rf spelieve/spelieve-secret/"

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npx cypress run

      - name: Archive cypress test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-artifacts
          path: |
            cypress/videos
        if: always()
